# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5b245dc1898611237fdaea31dcdec7fe2436223b3f8b5e229fa210b254d7641c470d3f27fe7604cbcf78f5690735ee3ac8c30a162f5fd23d1e04a0954c1957d0

test:
  secret_key_base: 78e34da7aa0c2ce2562eff4c17a11f320c4006889b54ff5e4e4a056994c950b549f74dbdf3cfae77c771e2e1d76b1b9224d3ec9ba769a43cff6300e8fbe83cc0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
